/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatRoom: typeof import('./src/renderer/components/ChatRoom.vue')['default']
    KIcon: typeof import('./src/renderer/components/KIcon.vue')['default']
    Markdown: typeof import('./src/renderer/components/Markdown.vue')['default']
    Menu: typeof import('./src/renderer/components/Menu.vue')['default']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardActions: typeof import('quasar')['QCardActions']
    QCardSection: typeof import('quasar')['QCardSection']
    QDialog: typeof import('quasar')['QDialog']
    QInput: typeof import('quasar')['QInput']
    QItem: typeof import('quasar')['QItem']
    QItemLabel: typeof import('quasar')['QItemLabel']
    QItemSection: typeof import('quasar')['QItemSection']
    QScrollArea: typeof import('quasar')['QScrollArea']
    QSelect: typeof import('quasar')['QSelect']
    QSpace: typeof import('quasar')['QSpace']
    Seeting: typeof import('./src/renderer/components/Seeting.vue')['default']
    Typing: typeof import('./src/renderer/components/Typing.vue')['default']
  }
}
