/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatRoom: typeof import('./src/components/ChatRoom.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    QBtn: typeof import('quasar')['QBtn']
    QInput: typeof import('quasar')['QInput']
    QItem: typeof import('quasar')['QItem']
    QItemLabel: typeof import('quasar')['QItemLabel']
    QItemSection: typeof import('quasar')['QItemSection']
    QScrollArea: typeof import('quasar')['QScrollArea']
    QSelect: typeof import('quasar')['QSelect']
    Typing: typeof import('./src/components/Typing.vue')['default']
  }
}
